# Generated by Django 6.1.1 on 2026-09-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatKlasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='riwayat/')),
                ('label_prediksi', models.CharField(max_length=50)),
                ('nama_tampilan', models.CharField(max_length=100)),
                ('keyakinan', models.FloatField(help_text='Persentase keyakinan, misal 81.9')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Riwayat Klasifikasi',
                'verbose_name_plural': 'Riwayat Klasifikasi',
                'ordering': ['-waktu'],
            },
        ),
    ]
