# Generated by Django 6.1.1 on 2026-09-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riwayatklasifikasi',
            name='is_confident',
            field=models.BooleanField(default=True, help_text='False kalau keyakinan di bawah ambang batas (tidak ditampilkan di Riwayat publik)'),
        ),
        migrations.AddField(
            model_name='riwayatklasifikasi',
            name='semua_hasil',
            field=models.JSONField(default=list, help_text='Breakdown confidence untuk semua kelas, dipakai buat render ulang chart'),
        ),
    ]
