# Generated by Django 6.1.1 on 2026-09-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_riwayatklasifikasi_is_confident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spesies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.SlugField(help_text="Harus sama dengan label di classifier.ml_utils.CLASS_NAMES, misal 'bekantan'.", unique=True)),
                ('nama_umum', models.CharField(help_text="Nama umum Bahasa Indonesia, misal 'Bekantan'.", max_length=100)),
                ('nama_ilmiah', models.CharField(help_text="Nama binomial, misal 'Nasalis larvatus'.", max_length=100)),
                ('otoritas_taksonomi', models.CharField(blank=True, help_text="Penulis & tahun pertama kali dideskripsikan, misal '(Wurmb, 1787)'.", max_length=100)),
                ('famili', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Spesies',
                'verbose_name_plural': 'Spesies',
                'ordering': ['nama_umum'],
            },
        ),
        migrations.CreateModel(
            name='FaktaSpesies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('taksonomi', 'Taksonomi'), ('status_konservasi', 'Status Konservasi'), ('ciri_fisik', 'Ciri Fisik / Identifikasi'), ('distribusi', 'Distribusi Geografis'), ('habitat', 'Habitat')], max_length=30)),
                ('isi', models.TextField(help_text='Isi informasi, ditulis ringkas dan sesuai sumber (hindari menambah klaim yang tidak ada di sumber).')),
                ('source_type', models.CharField(choices=[('iucn_red_list', 'IUCN Red List of Threatened Species'), ('mdd', 'Mammal Diversity Database (MDD)'), ('jurnal_ilmiah', 'Jurnal ilmiah (peer-reviewed)'), ('buku_monograf', 'Buku / Monograf / Taxonomic Revision'), ('institusi_resmi', 'Institusi resmi (BKSDA, LIPI/BRIN, IUCN SSC, dst.)')], max_length=30)),
                ('source_title', models.CharField(help_text="Judul rujukan persis, misal 'Nasalis larvatus. The IUCN Red List of Threatened Species 2020: e.T14352A17945165'.", max_length=300)),
                ('source_author', models.CharField(blank=True, help_text="Penulis/tim asesmen, misal 'Boonratana, R. et al.'", max_length=300)),
                ('source_year', models.PositiveIntegerField(blank=True, help_text='Tahun publikasi/asesmen sumber.', null=True)),
                ('source_doi', models.CharField(blank=True, help_text="DOI jika tersedia, misal '10.2305/IUCN.UK.2020-2.RLTS.T14352A17945165.en'.", max_length=150)),
                ('source_url', models.URLField(help_text='Tautan langsung ke sumber (halaman spesies IUCN/MDD, atau DOI paper).', max_length=500)),
                ('source_date', models.DateField(help_text='Tanggal data ini diakses/diverifikasi dari sumber (tanggal akses).')),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan, misal jika ada perbedaan pendapat antar sumber.')),
                ('spesies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fakta', to='classifier.spesies')),
            ],
            options={
                'verbose_name': 'Fakta Spesies',
                'verbose_name_plural': 'Fakta Spesies',
                'ordering': ['spesies', 'kategori'],
                'constraints': [models.UniqueConstraint(fields=('spesies', 'kategori'), name='unique_kategori_per_spesies')],
            },
        ),
    ]
