# Generated by Django 6.1.1 on 2026-09-20 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0004_seed_data_spesies'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoObservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='observasi/')),
                ('lokasi', models.CharField(blank=True, help_text="Lokasi observasi, misal 'Taman Nasional Tanjung Puting, Kalimantan Tengah'.", max_length=200)),
                ('tanggal_diambil', models.DateField(blank=True, help_text='Tanggal foto diambil / observasi dilakukan (bukan tanggal diunggah ke sistem ini).', null=True)),
                ('fotografer', models.CharField(blank=True, help_text='Nama observer/fotografer, jika diketahui.', max_length=150)),
                ('sumber_platform', models.CharField(blank=True, default='iNaturalist', help_text="Platform sumber observasi, misal 'iNaturalist'.", max_length=100)),
                ('sumber_url', models.URLField(blank=True, help_text='Tautan ke observasi asli.', max_length=500)),
                ('lisensi', models.CharField(blank=True, help_text="Lisensi foto, misal 'CC-BY-NC 4.0'.", max_length=100)),
                ('catatan', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil, angka kecil di depan.')),
                ('spesies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_observasi', to='classifier.spesies')),
            ],
            options={
                'verbose_name': 'Foto Observasi',
                'verbose_name_plural': 'Foto Observasi',
                'ordering': ['spesies', 'urutan', 'id'],
            },
        ),
    ]
